data:
  path: Countdown-Tasks-3to4
  test_size: 100
model:
  device: cuda
  dtype: bfloat16
  pretrained_model_path: Qwen2.5-0.5B-Instruct
training:
  batch_size: 64
  betas:
  - 0.9
  - 0.999
  ckpt_dir: ../results_grpo/countdown_0.5B_baseline_vs_softmax_20251204_185215/baseline/checkpoints
  ckpt_save_interval: 50
  eval_interval: 10
  learning_rate: 1.0e-06
  log_dir: ../results_grpo/countdown_0.5B_baseline_vs_softmax_20251204_185215/baseline/logs
  max_gen_len: 1024
  max_grad_norm: 1.0
  max_prompt_len: 512
  memory_efficient_adamw: true
  micro_batch_size: 2
  num_questions_per_batch: 8
  random_seed: 1337
  skip_unfinished_episodes: false
  weight_decay: 0.0
